import type { AgentDefinition } from './contracts.js';

export const AGENT_CATALOG: readonly AgentDefinition[] = [
  {
    id: 'data-quality',
    name: 'Data Quality Agent',
    purpose: 'Detect missing, stale, duplicate and inconsistent source data.',
    capabilities: ['data-quality'],
    allowedActionModes: ['read', 'analyse', 'draft'],
    allowedToolIds: ['maximo.read', 'finance.read', 'contract.read'],
    mayUseModel: false,
  },
  {
    id: 'asset-intelligence',
    name: 'Asset Intelligence Agent',
    purpose: 'Explain asset health, degradation and failure-risk drivers.',
    capabilities: ['asset-health', 'failure-risk', 'maintenance-priority'],
    allowedActionModes: ['read', 'analyse', 'draft', 'propose_write'],
    allowedToolIds: ['maximo.read', 'condition.read', 'inspection.read'],
    mayUseModel: true,
  },
  {
    id: 'maintenance-kpi',
    name: 'Maintenance KPI Agent',
    purpose: 'Explain deterministic KPI results, variance and exceptions.',
    capabilities: ['maintenance-kpi', 'exception-analysis'],
    allowedActionModes: ['read', 'analyse', 'draft'],
    allowedToolIds: ['maximo.read', 'contract.read'],
    mayUseModel: true,
  },
  {
    id: 'reporting',
    name: 'Reporting Agent',
    purpose: 'Draft monthly, quarterly and annual narratives from approved facts.',
    capabilities: ['monthly-report', 'quarterly-report', 'annual-report'],
    allowedActionModes: ['read', 'analyse', 'draft'],
    allowedToolIds: ['maximo.read', 'finance.read', 'contract.read', 'memory.read'],
    mayUseModel: true,
  },
  {
    id: 'executive-briefing',
    name: 'Executive Briefing Agent',
    purpose: 'Convert approved exceptions into concise decision-ready briefings.',
    capabilities: ['executive-briefing'],
    allowedActionModes: ['read', 'analyse', 'draft'],
    allowedToolIds: ['memory.read', 'contract.read'],
    mayUseModel: true,
  },
  {
    id: 'contract-context',
    name: 'Contract Context Agent',
    purpose: 'Retrieve approved clauses, thresholds, evidence rules and reporting duties.',
    capabilities: ['contract-context'],
    allowedActionModes: ['read', 'analyse', 'draft'],
    allowedToolIds: ['contract.read'],
    mayUseModel: true,
  },
  {
    id: 'finance-context',
    name: 'Finance Context Agent',
    purpose: 'Retrieve invoice, payment, variation and workflow status.',
    capabilities: ['finance-context'],
    allowedActionModes: ['read', 'analyse', 'draft'],
    allowedToolIds: ['finance.read'],
    mayUseModel: false,
  },
] as const;
